### ISSUE TITLE
Add about and acknowledgement pages

### ISSUE THREAD

**Issue by Orionsgate** [wonjoonSeol/ScienceScape#108]
Most links in the navigation menu currently don't go anywhere and an error is displayed. This issue is to ensure that all hanging/loose links lead somewhere.

**Comment by bforsyth927** [comment]
I added a simple About page that could do with some editing. Feel free to contribute anybody who has the time.

**Comment by Orionsgate** [comment]
All changes to the 'About' section of the site should go under this issue.

**Comment by nicolasvolken** [comment]
Relates to #152
