### ISSUE TITLE
Add about section

### ISSUE THREAD

**Issue by AJerm** [wonjoonSeol/ScienceScape#152]

**Comment by AJerm** [comment]
@nicolasvolken 
@saadmansakib 
@bforsyth927 
@mmuresanpaul 
@Orionsgate 
@wonjoonSeol 
@BadButNotBoujee 
@JHinshelwood 

Hey guys, can you all reply with links to the following if you'd like them linked from the 'Built by' section of the about page: 

- Twitter
- LinkedIn 
- GitHub

https://sciencescape.herokuapp.com/about/

Also, I've made space for where we can put a load of icons to represent what skills we all used when we worked on the project.

For now there's:

- [ ] Design
- [ ] Sigma JS
- [ ] Django
- [ ] Javascript
- [ ] CSS
- [ ] HTML5
- [ ] Databases
- [ ] Deployment
- [ ] Documentation
- [ ] Testing

Please let me know which ones you'd like by your name starting from the most important first.
If you want to add some new skills just add it to your list when you reply and I'll try to find a corresponding icon.

If you want a different photo then paste a link or upload the image here.

**Comment by mmuresanpaul** [comment]
Maybe add one for scripts(bibliotools refactoring). 
A nice icon for it: https://fontawesome.com/icons/terminal?style=solid

**Comment by nicolasvolken** [comment]
My info:
Linked in: https://www.linkedin.com/in/nicolasvolken
Website: www.nicolasvolken.com
Github: @nicolasvolken

Back-end Scripts (Bibliotools refactoring)
Refactoring
Design
Django
Deployment
Documentation
Testing front-end
Testing back-end

**Comment by nicolasvolken** [comment]
Thanks 😊

**Comment by Orionsgate** [comment]
- Swap 'Built with' and 'Built by' sections
- Remove 'Demo' button

**Comment by wonjoonSeol** [comment]
My info:
Linked in: https://www.linkedin.com/in/wonjoonseol/
Website: https://wonjoonseol.github.io/
Github: @wonjoonseol

Back-end Scripts (Bibliotools refactoring)
Refactoring
Architecture design and class diagram
Django & Heroku Deployment
Postgres Databases setup
Front-end testing

**Comment by saadmansakib** [comment]
LinkedIn: https://www.linkedin.com/in/saadman-sakib/
Website: www.saadmansakib.com
Github: @saadmansakib

Django
Python
Javascript
Sigma JS
CSS
HTML5
Design
Testing

**Comment by mmuresanpaul** [comment]
## My info:

- [**LinkedIn**](https://www.linkedin.com/in/paul-mure%C8%99an-729253b1/)
- [**Github**](https://github.com/mmuresanpaul)

## Worked on:

- Back-end Scripts (Bibliotools refactoring)
- Refactoring
- Back-end Testing
- Design
- CSS
- HTML5
- Javascript

**Comment by BadButNotBoujee** [comment]
Github: @BadButNotBoujee

Worked on:
Front end framework, functionality and helped with interfacing. 

Using:
Javascript
Python using Django Framework
HTML

**Comment by JHinshelwood** [comment]
github @jhinshelwood
Worked on front end framework and testing
using
python w/django, html, javascript
