### ISSUE TITLE
Fix file disclosure

### ISSUE THREAD

**Issue by nicolasvolken** [wonjoonSeol/ScienceScape#173]

**Comment by nicolasvolken** [comment]
We need to fix psycopg import.

**Comment by wonjoonSeol** [comment]
Try importing psycopg2-binary instead, changing the dependency to psycopg2-binary excludes people that have problems with the psycopg2 binary wheel package from using pgcli >= 1.9.0.

**Comment by nicolasvolken** [comment]
Psycopg2-binary is not accepted by heroku. We need to revert back to previous import

**Comment by nicolasvolken** [comment]
File disclosure is fixed.
