### ISSUE TITLE
Clean up existing codebase

### ISSUE THREAD

**Issue by bforsyth927** [wonjoonSeol/ScienceScape#18]
We need to perform some static analysis to make the existing bibliotools code more streamlined and elegant. 

If you decide to tackle a particular file, please post below which ones you are working on so we avoid conflicts.

**Comment by nicolasvolken** [comment]
I will start with "cleaning up" the following files: merging_corpus.py, corpus_parsed_overview.py, filter_and_network_ref.py, parse_and_group.py

**Comment by nicolasvolken** [comment]
In parser.py, the header codes (e.g. 'PY', 'C1') are hardcoded. In case the data bank change their data, I will add variables to hold them, until a centralised code database is set up in config.py

**Comment by nicolasvolken** [comment]
See commit https://github.com/wonjoonSeol/ScienceScape/commit/3faf93164a013932c6b881a32d204254e71e75ca

**Comment by bforsyth927** [comment]
From here I'll take `add_anotations_to_ref_network`.

**Comment by bforsyth927** [comment]
I conducted some further refactoring to `corpus_parsed_overview`, `merging_corpus`, and `parser`.

**Comment by nicolasvolken** [comment]
Some more refactoring has been done to files, in preparation for efficient and complete unit testing.

**Comment by nicolasvolken** [comment]
Bibliotools is now refactored, tested and redesigned.
It is now easier for future developers to build upon Bibliotools3.0.
