### ISSUE TITLE
Solve Heroku graph showing problem

### ISSUE THREAD

**Issue by nicolasvolken** [wonjoonSeol/ScienceScape#202]

**Comment by nicolasvolken** [comment]
The graphs are not showing on Heroku, even though they are displayed locally

**Comment by wonjoonSeol** [comment]
Deployment logs
[heroku_logs.txt](https://github.com/wonjoonSeol/ScienceScape/files/1837885/heroku_logs.txt)

**Comment by nicolasvolken** [comment]
**Update**
During the team meeting yesterday, the team has decided **not to deploy the website on Heroku.** The reason is that Heroku is a "_read-only" server,_ and it is therefore not possible to create/delete folders and move data around the website, which is critical to our application's purpose.
