### ISSUE TITLE
Swap plaintext logo for image

### ISSUE THREAD

**Issue by Orionsgate** [wonjoonSeol/ScienceScape#254]
<img src="/images/sciencescapes-logo.png?raw=true" width="20%" align="left">

<h2 align="right">Something wrong?</h2>

Issue description:

### 1. What is the issue?
The website does not use Nicolas' logo and instead uses a rich text formatted approximation of it.
<hr>

### 2. What can be done to resolve the issue?
Replace `<h1></h1>` with `<img>`
<hr>

### 3. Links/attachments RELEVANT to this issue
N/A
<hr>

<br>

Thank you for bringing this issue to our attention.

>By sumbitting this issue, I declare that this issue complies with the ScienceScapeS code of conduct, contributing guidelines and license.
>Any issue not complying with these guidelines will be closed by a representative.

**Comment by AJerm** [comment]
![image](https://user-images.githubusercontent.com/1643439/37909045-c7473e32-3101-11e8-8586-91bec7594c91.png)
